CREATE TABLE `events` (
  `event_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `featured_image` VARCHAR(45) NOT NULL,
  `banner_image` VARCHAR(45) NOT NULL,
  `short_description` VARCHAR(100) NOT NULL,
  `departure_date` DATETIME NOT NULL,
  `departure_place_name` VARCHAR(100) NOT NULL,
  `departure_place_url_map` TEXT NULL,
  `arrival_place_name` VARCHAR(100) NOT NULL AFTER `status_id`,
  `enrollment_start_date` DATETIME NOT NULL,
  `enrollment_end_date` DATETIME NOT NULL,
  `slug` TEXT NOT NULL,
  `status_id` INT(1) NOT NULL,
  PRIMARY KEY (`event_id`));